### ISSUE TITLE
Basic example crashes

### ISSUE THREAD

**Issue by danaugrs** [planetscale/planetscale-node#18]
Running the basic example in the README.md crashes with:
```
PS C:\projects\planetscale-node-test> node .\test.js
C:\projects\planetscale-node-test\node_modules\planetscale-node\dist\index.js:38
            throw new Error(`HTTP ${status}`);
                  ^

Error: HTTP 404
    at PSDB.createConnection (C:\projects\planetscale-node-test\node_modules\planetscale-node\dist\index.js:38:19)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async PSDB.query (C:\projects\planetscale-node-test\node_modules\planetscale-node\dist\index.js:21:32)
    at async main (C:\projects\planetscale-node-test\test.js:5:28)
```
Code, for reference:
```js
const { PSDB } = require('planetscale-node')
const conn = new PSDB('main')

async function main() {
  const [rows, fields] = await conn.query('select * from reminders')
  console.log(rows, fields)
}

main()
```

**Comment by danaugrs** [comment]
Nevermind - works after waiting a bit!

**Comment by jasonsilberman** [comment]
@danaugrs I am having the same issue. Did you do anything to fix your issue? I am getting an `HTTP 404` error. How long did you have to wait?

**Comment by samstr** [comment]
Same issue here. Will wait longer. Been a couple of hours
